[telegram]
api_id = "24897048"
api_hash = "9147c292b0dfc171e4d7e76293497742"
group_name = "researchreportss', 'indian_stock_news_updates"

[slack]
webhook = "https://hooks.slack.com/services/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"
